{
  "openapi": "3.0.0",
  "paths": {
    "/users": {
      "post": {
        "operationId": "UsersController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully created a user.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserDto"
                }
              }
            }
          }
        },
        "summary": "Create a user.",
        "tags": [
          "users"
        ]
      },
      "get": {
        "operationId": "UsersController_getAll",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successfully retrieved all users.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/UserDto"
                  }
                }
              }
            }
          }
        },
        "summary": "Return all users.",
        "tags": [
          "users"
        ]
      }
    },
    "/users/{id}": {
      "get": {
        "operationId": "UsersController_getById",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved user by id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserDto"
                }
              }
            }
          }
        },
        "summary": "Return user by id.",
        "tags": [
          "users"
        ]
      }
    },
    "/cities": {
      "post": {
        "operationId": "CitiesController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "The data to create new city",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCityDto"
              },
              "examples": {
                "single": {
                  "value": {
                    "name": "Amsterdam",
                    "country": "Netherlands",
                    "search": "Amsterdam",
                    "lat": 52.1234,
                    "lng": 12.1234,
                    "seaside": true
                  }
                },
                "multiple": {
                  "value": [
                    {
                      "id": 1,
                      "name": "Amsterdam",
                      "country": "Netherlands",
                      "search": "Amsterdam",
                      "lat": 52.1234,
                      "lng": 12.1234,
                      "seaside": true
                    },
                    {
                      "id": 2,
                      "name": "Belgrade",
                      "country": "Serbia",
                      "search": "Belgrade",
                      "lat": 52.1234,
                      "lng": 12.1234,
                      "seaside": true
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully created a city",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CityDto"
                },
                "examples": {
                  "single": {
                    "summary": "Single created city",
                    "value": {
                      "id": 1,
                      "name": "Amsterdam",
                      "country": "Netherlands",
                      "search": "Amsterdam",
                      "lat": 52.1234,
                      "lng": 12.1234,
                      "seaside": true
                    }
                  },
                  "multiple": {
                    "summary": "Count",
                    "value": {
                      "count": 10
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Create the new city.",
        "tags": [
          "cities"
        ]
      },
      "get": {
        "operationId": "CitiesController_getAll",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successfully retrieved cities.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CityDto"
                  }
                },
                "examples": {
                  "application/json": {
                    "summary": "City DTO array",
                    "value": [
                      {
                        "id": 1,
                        "name": "Amsterdam",
                        "country": "Netherlands",
                        "search": "Amsterdam",
                        "lat": 52.1234,
                        "lng": 12.1234,
                        "seaside": true
                      },
                      {
                        "id": 2,
                        "name": "Belgrade",
                        "country": "Serbia",
                        "search": "Belgrade",
                        "lat": 52.1234,
                        "lng": 12.1234,
                        "seaside": false
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "summary": "Return all cities.",
        "tags": [
          "cities"
        ]
      },
      "put": {
        "operationId": "CitiesController_update",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "The data to update city",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCityDto"
              },
              "examples": {
                "single": {
                  "value": {
                    "id": 1,
                    "name": "Amsterdam",
                    "country": "Netherlands",
                    "search": "Amsterdam",
                    "lat": 52.1234,
                    "lng": 12.1234,
                    "seaside": true
                  }
                },
                "multiple": {
                  "value": [
                    {
                      "id": 1,
                      "name": "Amsterdam",
                      "country": "Netherlands",
                      "search": "Amsterdam",
                      "lat": 52.1234,
                      "lng": 12.1234,
                      "seaside": true
                    },
                    {
                      "id": 2,
                      "name": "Belgrade",
                      "country": "Serbia",
                      "search": "Belgrade",
                      "lat": 52.1234,
                      "lng": 12.1234,
                      "seaside": false
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully updated cities.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CityDto"
                  }
                },
                "examples": {
                  "single": {
                    "summary": "Single updated city",
                    "value": {
                      "id": 1,
                      "name": "Amsterdam",
                      "country": "Netherlands",
                      "search": "Amsterdam",
                      "lat": 52.1234,
                      "lng": 12.1234,
                      "seaside": true
                    }
                  },
                  "multiple": {
                    "summary": "Multiple updated cities",
                    "value": [
                      {
                        "id": 1,
                        "name": "Amsterdam",
                        "country": "Netherlands",
                        "search": "Amsterdam",
                        "lat": 52.1234,
                        "lng": 12.1234,
                        "seaside": true
                      },
                      {
                        "id": 2,
                        "name": "Belgrade",
                        "country": "Serbia",
                        "search": "Belgrade",
                        "lat": 52.1234,
                        "lng": 12.1234,
                        "seaside": false
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "summary": "Update cities",
        "tags": [
          "cities"
        ]
      }
    },
    "/cities/{id}": {
      "get": {
        "operationId": "CitiesController_getById",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved city by id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CityDto"
                },
                "examples": {
                  "application/json": {
                    "summary": "City DTO",
                    "value": {
                      "id": 1,
                      "name": "Amsterdam",
                      "country": "Netherlands",
                      "search": "Amsterdam",
                      "lat": 52.1234,
                      "lng": 12.1234,
                      "seaside": true
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Return city by id.",
        "tags": [
          "cities"
        ]
      },
      "delete": {
        "operationId": "CitiesController_delete",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully deleted city by id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CityDto"
                },
                "examples": {
                  "application/json": {
                    "summary": "City DTO",
                    "value": {
                      "id": 1,
                      "name": "Amsterdam",
                      "country": "Netherlands",
                      "search": "Amsterdam",
                      "lat": 52.1234,
                      "lng": 12.1234,
                      "seaside": true
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Delete city by id.",
        "tags": [
          "cities"
        ]
      }
    },
    "/years": {
      "post": {
        "operationId": "YearsController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "The data to create new city",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateYearDto"
              },
              "examples": {
                "single": {
                  "value": {
                    "year": 2020
                  }
                },
                "multiple": {
                  "value": [
                    {
                      "year": 2020
                    },
                    {
                      "year": 2021
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully created a year",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/YearDto"
                },
                "examples": {
                  "single": {
                    "summary": "Year DTO",
                    "value": {
                      "id": 1,
                      "year": 2020
                    }
                  },
                  "multiple": {
                    "summary": "Count",
                    "value": {
                      "count": 10
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Create new year.",
        "tags": [
          "years"
        ]
      },
      "get": {
        "operationId": "YearsController_getAll",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successfully retrieved years.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/YearDto"
                  }
                },
                "examples": {
                  "application/json": {
                    "summary": "Year DTO array",
                    "value": [
                      {
                        "id": 1,
                        "year": 2020
                      },
                      {
                        "id": 2,
                        "year": 2021
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "summary": "Return all years.",
        "tags": [
          "years"
        ]
      }
    },
    "/years/{id}": {
      "get": {
        "operationId": "YearsController_getById",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved year by id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/YearDto"
                },
                "examples": {
                  "application/json": {
                    "summary": "Year DTO",
                    "value": {
                      "id": 1,
                      "year": 2020
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Return year by id.",
        "tags": [
          "years"
        ]
      }
    },
    "/products": {
      "post": {
        "operationId": "ProductsController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "The data to create new product",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductDto"
              },
              "examples": {
                "single": {
                  "value": {
                    "name": "men shoes",
                    "categoryId": 5,
                    "unit": "1 pair",
                    "description": "1 pair of leather men shoes",
                    "type": "HISTORICAL"
                  }
                },
                "multiple": {
                  "value": [
                    {
                      "name": "men shoes",
                      "categoryId": 5,
                      "unit": "1 pair",
                      "description": "1 pair of leather men shoes",
                      "type": "HISTORICAL"
                    },
                    {
                      "name": "internet",
                      "categoryId": 6,
                      "unit": "monthly subscription",
                      "description": "1 month internet subscription",
                      "type": "HISTORICAL"
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully created a product",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductDto"
                },
                "examples": {
                  "single": {
                    "summary": "Product DTO",
                    "value": {
                      "id": 1,
                      "name": "men shoes",
                      "categoryId": 5,
                      "unit": "1 pair",
                      "description": "1 pair of leather men shoes",
                      "type": "HISTORICAL"
                    }
                  },
                  "multiple": {
                    "summary": "Count",
                    "value": {
                      "count": 10
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Create the new product.",
        "tags": [
          "products"
        ]
      },
      "get": {
        "operationId": "ProductsController_getAll",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successfully retrieved products.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ProductDto"
                  }
                },
                "examples": {
                  "application/json": {
                    "summary": "Product DTO array",
                    "value": [
                      {
                        "id": 1,
                        "name": "man shoes",
                        "categoryId": 5,
                        "unit": "1 pair",
                        "description": "1 pair of leather man shoes",
                        "type": "HISTORICAL"
                      },
                      {
                        "id": 2,
                        "name": "internet",
                        "categoryId": 6,
                        "unit": "monthly subscription",
                        "description": "1 month internet subscription",
                        "type": "HISTORICAL"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "summary": "Return all products.",
        "tags": [
          "products"
        ]
      },
      "put": {
        "operationId": "ProductsController_update",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "The data to create new product",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProductDto"
              },
              "examples": {
                "single": {
                  "value": {
                    "id": 1,
                    "name": "men shoes",
                    "categoryId": 5,
                    "unit": "1 pair",
                    "description": "1 pair of leather men shoes",
                    "type": "HISTORICAL"
                  }
                },
                "multiple": {
                  "value": [
                    {
                      "id": 1,
                      "name": "men shoes",
                      "categoryId": 5,
                      "unit": "1 pair",
                      "description": "1 pair of leather men shoes",
                      "type": "HISTORICAL"
                    },
                    {
                      "id": 2,
                      "name": "internet",
                      "categoryId": 6,
                      "unit": "monthly subscription",
                      "description": "1 month internet subscription",
                      "type": "HISTORICAL"
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully updated products.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ProductDto"
                  }
                },
                "examples": {
                  "single": {
                    "summary": "Single updated product",
                    "value": {
                      "id": 1,
                      "name": "men shoes",
                      "categoryId": 5,
                      "unit": "1 pair",
                      "description": "1 pair of leather men shoes",
                      "type": "HISTORICAL"
                    }
                  },
                  "multiple": {
                    "summary": "Single updated product",
                    "value": [
                      {
                        "id": 1,
                        "name": "men shoes",
                        "categoryId": 5,
                        "unit": "1 pair",
                        "description": "1 pair of leather men shoes",
                        "type": "HISTORICAL"
                      },
                      {
                        "id": 2,
                        "name": "internet",
                        "categoryId": 6,
                        "unit": "monthly subscription",
                        "description": "1 month internet subscription",
                        "type": "HISTORICAL"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "summary": "Update products",
        "tags": [
          "products"
        ]
      }
    },
    "/products/{id}": {
      "get": {
        "operationId": "ProductsController_getById",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved product by id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductDto"
                },
                "examples": {
                  "application/json": {
                    "summary": "Product DTO",
                    "value": {
                      "id": 1,
                      "name": "men shoes",
                      "categoryId": 5,
                      "unit": "1 pair",
                      "description": "1 pair of leather men shoes",
                      "type": "HISTORICAL"
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Return product by id.",
        "tags": [
          "products"
        ]
      },
      "delete": {
        "operationId": "ProductsController_delete",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully deleted product by id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProductDto"
                },
                "examples": {
                  "application/json": {
                    "summary": "Product DTO",
                    "value": {
                      "id": 1,
                      "name": "men shoes",
                      "categoryId": 1,
                      "unit": "1 pair",
                      "description": "1 pair of leather men shoes",
                      "type": "HISTORICAL"
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Delete product by id.",
        "tags": [
          "products"
        ]
      }
    },
    "/categories": {
      "post": {
        "operationId": "CategoriesController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "The data to create new category",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCategoryDto"
              },
              "examples": {
                "single": {
                  "value": {
                    "name": "Markets"
                  }
                },
                "multiple": {
                  "value": [
                    {
                      "name": "Markets"
                    },
                    {
                      "name": "Restaurants"
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully created a category",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CategoryDto"
                },
                "examples": {
                  "single": {
                    "summary": "Category DTO",
                    "value": {
                      "id": 1,
                      "name": "Markets"
                    }
                  },
                  "multiple": {
                    "summary": "Count",
                    "value": {
                      "count": 10
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Create the new category.",
        "tags": [
          "categories"
        ]
      },
      "get": {
        "operationId": "CategoriesController_getAll",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successfully retrieved categories.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CategoryDto"
                  }
                },
                "examples": {
                  "application/json": {
                    "summary": "Category DTO array",
                    "value": [
                      {
                        "id": 1,
                        "name": "Markets"
                      },
                      {
                        "id": 2,
                        "name": "Restaurants"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "summary": "Return all categories.",
        "tags": [
          "categories"
        ]
      },
      "put": {
        "operationId": "CategoriesController_update",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "The data to update category",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCategoryDto"
              },
              "examples": {
                "single": {
                  "value": {
                    "id": 1,
                    "name": "Markets"
                  }
                },
                "multiple": {
                  "value": [
                    {
                      "id": 1,
                      "name": "Markets"
                    },
                    {
                      "id": 2,
                      "name": "Restaurants"
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully updated categories.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/CategoryDto"
                  }
                },
                "examples": {
                  "single": {
                    "summary": "Single updated category",
                    "value": {
                      "id": 1,
                      "name": "Markets"
                    }
                  },
                  "multiple": {
                    "summary": "Multiple updated categories",
                    "value": [
                      {
                        "id": 1,
                        "name": "Markets"
                      },
                      {
                        "id": 2,
                        "name": "Restaurants"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "summary": "Update categories",
        "tags": [
          "categories"
        ]
      }
    },
    "/categories/{id}": {
      "get": {
        "operationId": "CategoriesController_getById",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved category by id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CategoryDto"
                },
                "examples": {
                  "application/json": {
                    "summary": "Category DTO",
                    "value": {
                      "id": 1,
                      "name": "Markets"
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Return category by id.",
        "tags": [
          "categories"
        ]
      },
      "delete": {
        "operationId": "CategoriesController_delete",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully deleted category by id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CategoryDto"
                },
                "examples": {
                  "application/json": {
                    "summary": "category DTO",
                    "value": {
                      "id": 1,
                      "name": "Markets"
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Delete category by id.",
        "tags": [
          "categories"
        ]
      }
    },
    "/prices": {
      "post": {
        "operationId": "PricesController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "The data to create new price",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreatePriceDto"
              },
              "examples": {
                "single": {
                  "value": {
                    "price": 300,
                    "top": 500,
                    "bottom": 200,
                    "currency": "EUR",
                    "cityId": 1,
                    "productId": 1,
                    "yearId": 1,
                    "priceType": "HISTORICAL"
                  }
                },
                "multiple": {
                  "value": [
                    {
                      "price": 300,
                      "top": 500,
                      "bottom": 200,
                      "currency": "EUR",
                      "cityId": 1,
                      "productId": 1,
                      "yearId": 1,
                      "priceType": "HISTORICAL"
                    },
                    {
                      "price": 200,
                      "top": 500,
                      "bottom": 200,
                      "currency": "EUR",
                      "cityId": 1,
                      "productId": 1,
                      "yearId": 1,
                      "priceType": "HISTORICAL"
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successfully created a price",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PriceDto"
                },
                "examples": {
                  "single": {
                    "summary": "Price DTO",
                    "value": {
                      "id": 1,
                      "price": 300,
                      "top": 500,
                      "bottom": 200,
                      "currency": "EUR",
                      "cityId": 1,
                      "productId": 1,
                      "yearId": 1,
                      "priceType": "HISTORICAL",
                      "createdAt": "2025-03-26T19:50:30.809Z",
                      "updatedAt": "2025-03-26T19:50:30.809Z"
                    }
                  },
                  "multiple": {
                    "summary": "Count",
                    "value": {
                      "count": 100
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Create the new price.",
        "tags": [
          "prices"
        ]
      },
      "get": {
        "operationId": "PricesController_getAll",
        "parameters": [
          {
            "name": "currency",
            "required": false,
            "in": "query",
            "schema": {
              "example": "EUR",
              "type": "string"
            }
          },
          {
            "name": "cityId",
            "required": false,
            "in": "query",
            "schema": {
              "example": 1,
              "type": "number"
            }
          },
          {
            "name": "productId",
            "required": false,
            "in": "query",
            "schema": {
              "example": 1,
              "type": "number"
            }
          },
          {
            "name": "yearId",
            "required": false,
            "in": "query",
            "schema": {
              "example": 1,
              "type": "number"
            }
          },
          {
            "name": "priceType",
            "required": false,
            "in": "query",
            "schema": {
              "example": "HISTORICAL",
              "type": "string",
              "enum": [
                "CURRENT",
                "HISTORICAL"
              ]
            }
          },
          {
            "name": "limit",
            "required": false,
            "in": "query",
            "description": "Items per page",
            "schema": {
              "example": 10,
              "type": "number"
            }
          },
          {
            "name": "offset",
            "required": false,
            "in": "query",
            "description": "Items to skip",
            "schema": {
              "example": 0,
              "type": "number"
            }
          },
          {
            "name": "sortBy",
            "required": false,
            "in": "query",
            "description": "Field to sort by",
            "schema": {
              "$ref": "#/components/schemas/Object"
            }
          },
          {
            "name": "order",
            "required": false,
            "in": "query",
            "description": "Sort order: asc or desc",
            "schema": {
              "example": "desc",
              "type": "string",
              "enum": [
                "asc",
                "desc"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved prices.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/PricePaginationDto"
                  }
                },
                "examples": {
                  "application/json": {
                    "summary": "price DTO array",
                    "value": {
                      "data": [
                        {
                          "id": 1,
                          "price": 300,
                          "top": 500,
                          "bottom": 200,
                          "currency": "EUR",
                          "cityId": 1,
                          "productId": 1,
                          "yearId": 1,
                          "priceType": "HISTORICAL",
                          "createdAt": "2025-03-26T19:50:30.809Z",
                          "updatedAt": "2025-03-26T19:50:30.809Z"
                        },
                        {
                          "id": 2,
                          "price": 400,
                          "top": 500,
                          "bottom": 200,
                          "currency": "EUR",
                          "cityId": 1,
                          "productId": 1,
                          "yearId": 1,
                          "priceType": "HISTORICAL",
                          "createdAt": "2025-03-26T19:50:30.809Z",
                          "updatedAt": "2025-03-26T19:50:30.809Z"
                        }
                      ],
                      "total": 100,
                      "limit": 10,
                      "page": 1
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Return all prices.",
        "tags": [
          "prices"
        ]
      },
      "put": {
        "operationId": "PricesController_update",
        "parameters": [],
        "requestBody": {
          "required": true,
          "description": "The data to update price",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreatePriceDto"
              },
              "examples": {
                "single": {
                  "value": {
                    "id": 1,
                    "price": 300,
                    "currency": "EUR",
                    "cityId": 1,
                    "productId": 1,
                    "yearId": 1,
                    "priceType": "HISTORICAL"
                  }
                },
                "multiple": {
                  "value": [
                    {
                      "id": 1,
                      "price": 300,
                      "top": 500,
                      "bottom": 200,
                      "currency": "EUR",
                      "cityId": 1,
                      "productId": 1,
                      "yearId": 1,
                      "priceType": "HISTORICAL"
                    },
                    {
                      "id": 2,
                      "price": 300,
                      "top": 500,
                      "bottom": 200,
                      "currency": "EUR",
                      "cityId": 1,
                      "productId": 1,
                      "yearId": 1,
                      "priceType": "HISTORICAL"
                    }
                  ]
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully updated prices.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/PriceDto"
                  }
                },
                "examples": {
                  "single": {
                    "summary": "Single updated price",
                    "value": {
                      "id": 1,
                      "price": 300,
                      "top": 500,
                      "bottom": 200,
                      "currency": "EUR",
                      "cityId": 1,
                      "productId": 1,
                      "yearId": 1,
                      "priceType": "HISTORICAL",
                      "createdAt": "2025-03-26T19:50:30.809Z",
                      "updatedAt": "2025-03-26T19:50:30.809Z"
                    }
                  },
                  "multiple": {
                    "summary": "Multiple updated prices",
                    "value": [
                      {
                        "id": 1,
                        "price": 300,
                        "top": 500,
                        "bottom": 200,
                        "currency": "EUR",
                        "cityId": 1,
                        "productId": 1,
                        "yearId": 1,
                        "priceType": "HISTORICAL",
                        "createdAt": "2025-03-26T19:50:30.809Z",
                        "updatedAt": "2025-03-26T19:50:30.809Z"
                      },
                      {
                        "id": 2,
                        "price": 400,
                        "top": 500,
                        "bottom": 200,
                        "currency": "EUR",
                        "cityId": 1,
                        "productId": 1,
                        "yearId": 1,
                        "priceType": "HISTORICAL",
                        "createdAt": "2025-03-26T19:50:30.809Z",
                        "updatedAt": "2025-03-26T19:50:30.809Z"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "summary": "Update prices",
        "tags": [
          "prices"
        ]
      }
    },
    "/prices/{id}": {
      "get": {
        "operationId": "PricesController_getById",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved price by id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PriceDto"
                },
                "examples": {
                  "application/json": {
                    "summary": "Price DTO",
                    "value": {
                      "id": 1,
                      "price": 300,
                      "top": 500,
                      "bottom": 200,
                      "currency": "EUR",
                      "cityId": 1,
                      "productId": 1,
                      "yearId": 1,
                      "priceType": "HISTORICAL",
                      "createdAt": "2025-03-26T19:50:30.809Z",
                      "updatedAt": "2025-03-26T19:50:30.809Z"
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Return price by id.",
        "tags": [
          "prices"
        ]
      },
      "delete": {
        "operationId": "PricesController_delete",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully deleted price by id.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PriceDto"
                },
                "examples": {
                  "application/json": {
                    "summary": "Price DTO",
                    "value": {
                      "id": 1,
                      "price": 300,
                      "top": 500,
                      "bottom": 200,
                      "currency": "EUR",
                      "cityId": 1,
                      "productId": 1,
                      "yearId": 1,
                      "priceType": "HISTORICAL",
                      "createdAt": "2025-03-26T19:50:30.809Z",
                      "updatedAt": "2025-03-26T19:50:30.809Z"
                    }
                  }
                }
              }
            }
          }
        },
        "summary": "Delete price by id.",
        "tags": [
          "prices"
        ]
      }
    }
  },
  "info": {
    "title": "My API",
    "description": "The API documentation",
    "version": "1.0",
    "contact": {}
  },
  "tags": [],
  "servers": [],
  "components": {
    "schemas": {
      "CreateUserDto": {
        "type": "object",
        "properties": {}
      },
      "UserDto": {
        "type": "object",
        "properties": {}
      },
      "CreateCityDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the city"
          },
          "country": {
            "type": "string",
            "description": "The country where the city is located"
          },
          "search": {
            "type": "string",
            "description": "Name used for numbeo search"
          },
          "lat": {
            "type": "number",
            "description": "Latitude of the city"
          },
          "lng": {
            "type": "number",
            "description": "Longitude of the city"
          },
          "seaside": {
            "type": "boolean",
            "description": "Is city on the seaside"
          }
        },
        "required": [
          "name",
          "country",
          "search",
          "lat",
          "lng",
          "seaside"
        ]
      },
      "CityDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "description": "The unique identifier of the city"
          },
          "name": {
            "type": "string",
            "description": "The name of the city"
          },
          "country": {
            "type": "string",
            "description": "The country where the city is located"
          },
          "search": {
            "type": "string",
            "description": "Name used for numbeo search"
          },
          "lat": {
            "type": "number",
            "description": "Latitude of the city"
          },
          "lng": {
            "type": "number",
            "description": "Longitude of the city"
          },
          "seaside": {
            "type": "boolean",
            "description": "Is city on the seaside"
          }
        },
        "required": [
          "id",
          "name",
          "country",
          "search",
          "lat",
          "lng",
          "seaside"
        ]
      },
      "CreateYearDto": {
        "type": "object",
        "properties": {
          "year": {
            "type": "number",
            "description": "The year number"
          }
        },
        "required": [
          "year"
        ]
      },
      "YearDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "description": "The unique identifier of the year"
          },
          "year": {
            "type": "number",
            "description": "The year number"
          }
        },
        "required": [
          "id",
          "year"
        ]
      },
      "ProductDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "description": "The unique identifier of the product"
          },
          "name": {
            "type": "string",
            "description": "Product name"
          },
          "categoryId": {
            "type": "number",
            "description": "Category id of the product"
          },
          "unit": {
            "type": "string",
            "description": "Product unit"
          },
          "description": {
            "type": "string",
            "description": "Product description, optional"
          },
          "type": {
            "type": "string",
            "description": "Product Type",
            "enum": [
              "ALL",
              "CURRENT",
              "HISTORICAL"
            ]
          }
        },
        "required": [
          "id",
          "name",
          "categoryId",
          "unit",
          "type"
        ]
      },
      "CreateCategoryDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "The name of the category"
          }
        },
        "required": [
          "name"
        ]
      },
      "CategoryDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "description": "The unique identifier of the category"
          },
          "name": {
            "type": "string",
            "description": "The name of the category"
          }
        },
        "required": [
          "id",
          "name"
        ]
      },
      "CreatePriceDto": {
        "type": "object",
        "properties": {
          "price": {
            "type": "number",
            "description": "The price value"
          },
          "top": {
            "type": "number",
            "description": "Top of the price range"
          },
          "bottom": {
            "type": "number",
            "description": "Bottom of the price range"
          },
          "currency": {
            "type": "string",
            "description": "The currency of the price"
          },
          "cityId": {
            "type": "number",
            "description": "The id of the city (cities table foreign key)"
          },
          "productId": {
            "type": "number",
            "description": "The id of the product (products table foreign key)"
          },
          "yearId": {
            "type": "number",
            "description": "The id of the year (years table foreign key)"
          },
          "priceType": {
            "type": "string",
            "description": "Price Type",
            "enum": [
              "CURRENT",
              "HISTORICAL"
            ]
          }
        },
        "required": [
          "price",
          "currency",
          "cityId",
          "productId",
          "yearId",
          "priceType"
        ]
      },
      "PriceDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number",
            "description": "The unique identifier of the price"
          },
          "price": {
            "type": "number",
            "description": "The price value"
          },
          "top": {
            "type": "number",
            "description": "Top of the price range"
          },
          "bottom": {
            "type": "number",
            "description": "Bottom of the price range"
          },
          "currency": {
            "type": "string",
            "description": "The currency of the price"
          },
          "cityId": {
            "type": "number",
            "description": "The id of the city (cities table foreign key)"
          },
          "productId": {
            "type": "number",
            "description": "The id of the product (products table foreign key)"
          },
          "yearId": {
            "type": "number",
            "description": "The id of the year (years table foreign key)"
          },
          "createdAt": {
            "format": "date-time",
            "type": "string",
            "description": "Date when the record was created",
            "example": "2025-03-26T12:00:00Z"
          },
          "updatedAt": {
            "format": "date-time",
            "type": "string",
            "description": "Date when the record was last updated",
            "example": "2025-03-26T12:00:00Z"
          },
          "priceType": {
            "type": "string",
            "description": "Price Type",
            "enum": [
              "CURRENT",
              "HISTORICAL"
            ]
          }
        },
        "required": [
          "id",
          "price",
          "currency",
          "cityId",
          "productId",
          "yearId",
          "priceType"
        ]
      },
      "Object": {
        "type": "object",
        "properties": {}
      },
      "PricePaginationDto": {
        "type": "object",
        "properties": {
          "data": {
            "description": "Array of prices matching the query filters",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PriceDto"
            }
          },
          "total": {
            "type": "number",
            "description": "Total number of prices matching the query filters",
            "example": 100
          },
          "limit": {
            "type": "number",
            "description": "Limit of items per page",
            "example": 10
          },
          "offset": {
            "type": "number",
            "description": "Offset of items to skip for pagination",
            "example": 1
          }
        },
        "required": [
          "data",
          "total",
          "limit",
          "offset"
        ]
      }
    }
  }
}